[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.15"

[lib]
path = "/dev/null"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/7b7a82e050ddb2a36b987e723d75219ab47e909b65814495a93c6f2cde4c86d1/kernel-5.15.110-70.143.amzn2.src.rpm"
sha512 = "b88ae74115a32ff72cf674b284269906157129d85556fbf28da696829187921c4285960a90141e1ecf790e4a5251be6603880e58e8492f1908efd35f2c2b170b"

[build-dependencies]
microcode = { path = "../microcode" }
