[package]
name = "kernel-5_10"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.10"

[lib]
path = "/dev/null"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/8888a1b6813024dbffc549d5388b972c5151222a8ebc99139d6c5da1c0100cbf/kernel-5.10.179-171.711.amzn2.src.rpm"
sha512 = "1c532197ee60d2039d54226b7d7b1e6bddaccd87f10e1c3fee676c3cb4ef8bd2ef321c702c975d94dffba347aadd37e8d3f093cdc054bcee7f50584784f359c3"

[build-dependencies]
microcode = { path = "../microcode" }
